language: node_js
sudo: false
node_js:
  - 8
  - 10
  - 12
script: npm test
notifications:
  email:
    on_success: change
    on_failure: change
after_success:
  - npm run coveralls
cache:
  directories:
  - node_modules
